import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppProvider } from './_components/appProvider'
import { NavWrapper } from '@/nav/_components/navWrapper'
import { Navbar } from '@/navbar/_components/navbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Navbar />
          <NavWrapper>
            {children}
          </NavWrapper>
        </AppProvider>
      </body>
    </html>
  )
}
