export enum SchoolSectionActionTypeEnum {
  SET_SCHOOL_SECTIONS = "SET_SCHOOL_SECTIONS",
  SET_SCHOOL_SUBJECT = "SET_SCHOOL_SUBJECT",
  SET_SCHOOL_CLASS = "SET_SCHOOL_CLASS",
  SET_SCHOOL_TERM = "SET_SCHOOL_TERM",
  SET_PROFESSOR = "SET_PROFESSOR",
  RESET = "RESET",
}
