export enum ManageStatusActionEnum {
  SET_SELECTED = "SET_SELECTED",
  SET_ACTION = "SET_ACTION",
  UPDATE_FETCH_PARAMS = "UPDATE_FETCH_PARAMS",
  SET_FETCH_RESULT = "SET_FETCH_RESULT",
  SET_COLLECTION_VIEW = "SET_COLLECTION_VIEW",
  RESET = "RESET",
}
